version: 2.1

parameters:
  PMBOT:
    type: boolean
    default: false
  PMBOT_UPDATE_ID:
    type: string
    default: ''

jobs:
  update:
    docker:
      - image: pmbot/bot
    environment:
      PMBOT_URL: http://2e104f18bb19.ngrok.io/
      # !!!!! place this in a secret environment variable !!!!!
      # https://docs.gitlab.com/ee/ci/variables/#create-a-custom-variable-in-the-ui
      PROJECT_TOKEN: ac39777e23c29cf7d48e9844829d9b7c
    steps:
      - checkout
      - run:
          command: |
            npm ci
            pmbot update --api-path /

  build:
    docker:
      - image: node:12-alpine`
    steps:
      - checkout
      - run: node --version

  notify:
    docker:
      - image: pmbot/tmp
    environment:
      PMBOT_URL: http://2e104f18bb19.ngrok.io/
      PMBOT_PROJECT_ID: 5f05e5891c0f29452c9d4bd8
      # !!!!! place this in a secret environment variable !!!!!
      # https://docs.gitlab.com/ee/ci/variables/#create-a-custom-variable-in-the-ui
      PROJECT_TOKEN: ac39777e23c29cf7d48e9844829d9b7c
    steps:
      - run:
          when: always
          command: pmbot nofity --api-path /

workflows:

  update:
    when: << pipeline.parameters.PMBOT >>
    jobs:
      - update
      - notify

  main:
    unless: << pipeline.parameters.PMBOT >>
    jobs:
      - build
      - notify
